= Latin-2-Assignments
:toc: left
:toclevels: 3
:sectids:
:sectlinks:
:sectanchors:
:sectnums:
:sectnumlevels: 2
//tag::Variables[]
:lesson1video: Lesson 1 https://drive.google.com/file/d/1RS8AATTHHyMtNJBVUBb8KBRNKwYUnvFF/view?usp=sharing[1080] https://drive.google.com/file/d/1P19C0n9WOwClvIL6FHoGER0F5FbP0pnK/view?usp=sharing[480]
:lesson2video: Lesson 2 https://drive.google.com/file/d/1QRQJBYO_GauTbJNi_lWgzeLUGfJi5xU2/view?usp=sharing[1080] https://drive.google.com/file/d/1P_W2MCK-uA9_DpcAaZJHKDzi2-ymcK7q/view?usp=sharing[480]
:lesson1-2video: Lesson 1-2 Review https://drive.google.com/file/d/1RAvjPvSeQ0hyhTHpPNG7319ApyoIk5lx/view?usp=sharing[1080] https://drive.google.com/file/d/1P3TPocK-y-WDWBRvGlQlgdfu5EsdAJXm/view?usp=sharing[480]
:lesson3video: Lesson 3 https://drive.google.com/file/d/1Qt6RWaNvJM83ES5HjP1pEeoLGf40Hj58/view?usp=sharing[1080] https://drive.google.com/file/d/1PE3VQ54d9oF8g8whSCH2c1YE09asvw0s/view?usp=sharing[480]
:lesson3bvideo: Lesson 3b https://drive.google.com/file/d/1Qn7EYqm1dqUpPaadxaxG4hPhXjhJCkwD/view?usp=sharing[1080] https://drive.google.com/file/d/1PqfrF0d4CkFKfJibze0E8OiKmdrxjzgj/view?usp=sharing[480]
:lesson4video: Lesson 4 https://drive.google.com/file/d/1QisciQuxo6dKKgInMal_IM1PZtR-QK4Z/view?usp=sharing[1080] https://drive.google.com/file/d/1PycSPT6J3WeFoV0JVBlfAkzX1t0Rbbzw/view?usp=sharing[480]
:lesson4bvideo: Lesson 4b https://drive.google.com/file/d/1QwsyL1erOMhI4yiCsqdyQM6ZjIYYWljG/view?usp=sharing[1080] https://drive.google.com/file/d/1PZrQwT5uZQxy61O6kjpwXAwKP6FvIXiZ/view?usp=sharing[480]
:lesson3-4video: Lesson 3-4 Review https://drive.google.com/file/d/1QIR8GJbEWcYkkbc8Y7zShy5KfsIq9oiU/view?usp=sharing[1080] https://drive.google.com/file/d/1Ppkg8ZEcCDpNdPW3LHEpljPXWa0F3ds2/view?usp=sharing[480]
:lesson5video: Lesson 5 https://drive.google.com/file/d/1QXTn5TZrP6fSmXAzmwhIxzIw816LF6tq/view?usp=sharing[1080] https://drive.google.com/file/d/1PRJnnV9qYsVKyAteqe0Nw-G7FrEVDGul/view?usp=sharing[480]
:lesson5bvideo: Lesson 5b https://drive.google.com/file/d/1RG5wWsC3TV6DVWy6mS_iF71yL7skDs5k/view?usp=sharing[1080] https://drive.google.com/file/d/1PXnnmPAmCAhD4utvBT_kGp-38_YfpyEH/view?usp=sharing[480]
:lesson6video: Lesson 6 https://drive.google.com/file/d/1Qt0dOWpBxRNyZ5utflbvZVG03OXAVDLG/view?usp=sharing[1080] https://drive.google.com/file/d/1P9ND4fa-DidkxfDxyMIqbFdvNa74zUfT/view?usp=sharing[480]
:lesson5-6video: Lesson 5-6 Review https://drive.google.com/file/d/1Qd__RijEKfyVKyohq_CVnAxglTSiU-by/view?usp=sharing[1080] https://drive.google.com/file/d/1PuQeccGdp9UO8Zbr34m8f655E42IKzdc/view?usp=sharing[480]
:lesson7video: Lesson 7 https://drive.google.com/file/d/1QUjYn2VwW8djGGC4k54fMPAD6ghboc4S/view?usp=sharing[1080] https://drive.google.com/file/d/1PGFSuXjMOSf-mU7PJnw2PhZJXcPMGIDH/view?usp=sharing[480]
:lesson8video: Lesson 8 https://drive.google.com/file/d/1QIc9bTujhbeuwklQNf9Hq8TOQ2JdlkWh/view?usp=sharing[1080] https://drive.google.com/file/d/1P8veT68BrgmFQhMSBiDNIIVzFjSDX5lO/view?usp=sharing[480]
:lesson8bvideo: Lesson 8b https://drive.google.com/file/d/1QUw_iDLf7l_7Wlm-iGUYvXMx7ki0pEUa/view?usp=sharing[1080] https://drive.google.com/file/d/1Q4iCnA4nMnDVtC3fFkq-N3GJLGFU0mqK/view?usp=sharing[480]
:lesson7-8video: Lesson 7-8 Review https://drive.google.com/file/d/1R2RkvYVAaxpFolufcm2ETvR-Yfja-tl2/view?usp=sharing[1080] https://drive.google.com/file/d/1P0fG2DTEe7AxCN8pKASy0bXM0zdO2bCD/view?usp=sharing[480]
:lesson9video: Lesson 9 https://drive.google.com/file/d/1QP-wkIufZGq73iTSToa2jaMqfh-K5MRI/view?usp=sharing[1080] https://drive.google.com/file/d/1P8Vh6UFYnZ87In3NQkIyeMcZ20T2lR6g/view?usp=sharing[480]
:lesson10video: Lesson 10 https://drive.google.com/file/d/1RCa81hpw8hUKw7yLbgzgL4MIgIpQ8PC-/view?usp=sharing[1080] https://drive.google.com/file/d/1PS-dQ4Z4CJ6LobbgfRqduoq-ShWB5bP6/view?usp=sharing[480]
:lesson9-10video: Lesson 9-10 Review https://drive.google.com/file/d/1QXR_P7OlZnaZJkH7s6DURAJY0jn9NlBI/view?usp=sharing[1080] https://drive.google.com/file/d/1PMxRERa1UOF5abwAGSrAUJUkXdr-RXf6/view?usp=sharing[480]
:lesson11video: Lesson 11 https://drive.google.com/file/d/1QURkMvKIlBQ8O8t5nNMqZFIGhXlyuXES/view?usp=sharing[1080] https://drive.google.com/file/d/1PgRhrngl2Z3N18Hv88r2xeYFUjPVPaJ2/view?usp=sharing[480]
:lesson11bvideo: Lesson 11b https://drive.google.com/file/d/1QSFvId-TwiqOeMmoS2s0B65Iv6JqRzDb/view?usp=sharing[1080] https://drive.google.com/file/d/1PrkfhwLmIvk2W7a9D7Uml3ZMzJ5iOBSv/view?usp=sharing[480]
:lesson12video: Lesson 12 https://drive.google.com/file/d/1QtfjxHhelejwCEVUJCwDwzb0BTg1nkcN/view?usp=sharing[1080] https://drive.google.com/file/d/1PijWja5fP4XUmo5v1I2gTd9QHx_QFMgT/view?usp=sharing[480]
:lesson12bvideo: Lesson 12b https://drive.google.com/file/d/1RGpBcho3OEgDDjtVvMRp9rW2le1dj0hQ/view?usp=sharing[1080] https://drive.google.com/file/d/1PTPMrX-ezv55jQgBQNorykhAp5yH4qOC/view?usp=sharing[480]
:lesson11-12video: Lesson 11-12 Review https://drive.google.com/file/d/1QnGxrn24-gN4xNqfEJni2AyFTcbqw3zF/view?usp=sharing[1080] https://drive.google.com/file/d/1PwERPaz_4qdHt1VwXtPaZ4ICHxiwZlcJ/view?usp=sharing[480]
:lesson13video: Lesson 13 https://drive.google.com/file/d/1QkM5uWVlRYBCrME6laDyZiPw9zTIKicz/view?usp=sharing[1080] https://drive.google.com/file/d/1PxUuv0fNwqimtkNzEZgjOTsUyqIfKnn6/view?usp=sharing[480]
:lesson14video: Lesson 14 https://drive.google.com/file/d/1QG38F9ed6EDl1mPbODzRbZ5PM-5Tni95/view?usp=sharing[1080] https://drive.google.com/file/d/1PNrzjcWrRPwHN_xQmhf7w4j0qiwrV_e8/view?usp=sharing[480]
:lesson13-14video: Lesson 13-14 https://drive.google.com/file/d/1QqJLMt6VVVB92s9YVoFBWBpmJhPPRkc-/view?usp=sharing[1080] https://drive.google.com/file/d/1Px0-8mY7BkV3HNu-2lmChGYl38ytPevK/view?usp=sharing[480]
:lesson15video: Lesson 15 https://drive.google.com/file/d/1RSI1HL75cawIEVsZH8RpLsH39fIsi2xZ/view?usp=sharing[1080] https://drive.google.com/file/d/1PBK4NaoHEvgK5GwPs7BYh8HMburOXquR/view?usp=sharing[480]
:lesson16video: Lesson 16 https://drive.google.com/file/d/1R-96eHKxPDPeCeQ2NHcdIP40l7pUakyQ/view?usp=sharing[1080] https://drive.google.com/file/d/1Ox1qVpkHUr2fWdUpFftpOylghPgT41qR/view?usp=sharing[480]
:lesson15-16video: Lesson 15-16 Review https://drive.google.com/file/d/1QDpN-72yg-NtaIdbDjiR-rvgj3N9Zv3z/view?usp=sharing[1080] https://drive.google.com/file/d/1PLVC80TQg0K_l6tvXllpzAQnbWE8Ny8f/view?usp=sharing[480]
:lesson17video: Lesson 17 https://drive.google.com/file/d/1QQgrt8XZw7dbDQhwtG6rjlcIRkmoF4an/view?usp=sharing[1080] https://drive.google.com/file/d/1P-7e598tloXAyBky-mHMQO12lp4PdRxP/view?usp=sharing[480]
:lesson18video: Lesson 18 https://drive.google.com/file/d/1QLcT84J8-LTFOKzOqiRIfX_dk89jW5Xc/view?usp=sharing[1080] https://drive.google.com/file/d/1Q2R0ZwGJoA-Y69oyFH45lcqVdyTxq9no/view?usp=sharing[480]
:lesson17-18video: Lesson 17-18 Reivew https://drive.google.com/file/d/1QW_m2FqeoS6lZJ0n4jSid21TdUzkPxMv/view?usp=sharing[1080] https://drive.google.com/file/d/1P3P_q-DBgFRinyaxmwXqLOMVzMIFe2Cl/view?usp=sharing[480]
:lesson19video: Lesson 19 https://drive.google.com/file/d/1RC5EoM7MJb4j56KjWI6EO0LKaNyLAixT/view?usp=sharing[1080] https://drive.google.com/file/d/1PRcdF5heUJBKhIY0LrBQj37fIuGgVUOc/view?usp=sharing[480]
:alphetbetvideo: Alphabet Video https://drive.google.com/file/d/1QR9yAIeZLsNw2rAz_vPEqlNbRnbarhcY/view?usp=sharing[1080] https://drive.google.com/file/d/1Q5hvBmIGim7u2ESPBISaL9U_94ZRZ0Iq/view?usp=sharing[480]
:lesson20video: Lesson 20 https://drive.google.com/file/d/1QV_Cy18NYrYBmqQDCTaMyxi89WUsmH2e/view?usp=sharing[1080]
:lesson19-20video: Lesson 19-20 https://drive.google.com/file/d/1QZPGk02wMbDwwxRXuQdck947xTk1q2pC/view?usp=sharing[1080]
:alphabetvideo: https://drive.google.com/file/d/1RIULPtac3bMb5YQzwrfsyn9V596A8gor/view?usp=sharing[1080]
:lesson21video: Lesson 21 https://drive.google.com/file/d/1QZVEo0zDoe_f6NvVugbs2S9Q7weYQWqz/view?usp=sharing[1080]

:lesson1-3vocabulary: https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Review Vocabulary for chapters 1-3]
:lesson4-6vocabulary: https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]
:lesson7-10vocabulary: https://drive.google.com/file/d/1N7Hsx0nAYDLthbF3SGIToEi2H_htXoqL/view?usp=share_link[Vocabulary for Chapters 7-10]
:lesson11-12vocabulary: https://drive.google.com/file/d/1m6tNzdxSSgOPQZ5S7aPw9zArmMmZ4wPW/view?usp=sharing[Vocabulary for Chapters 11-12]
:lesson13-14vocabulary: https://drive.google.com/file/d/1aDf-hfaGZY6Sb7thlZ_7T2yI-CBGqAo_/view?usp=share_link
:lesson13-14script: https://drive.google.com/file/d/1aE6iTpdNT16xm3UdAVXqT5OaTj2UCnYh/view?usp=share_link[Script for Chatpers 13-14]

//end::Variables[]
== starting with 037

https://drive.google.com/file/d/1QXwp39y6J51Lg6DQ6aVlZ5Gj0U-ld-7_/view?usp=sharing[1080]
https://drive.google.com/file/d/1RCopf8AKUsb1XU-eCFdBNzgdIaqbrw1t/view?usp=sharing[1080]
https://drive.google.com/file/d/1QqBqPYZK5E7WUaxSC666yKqmaxR7QscG/view?usp=sharing[1080]
https://drive.google.com/file/d/1QY_qZZodypihNf_fQW1j2APtT9BfEOw9/view?usp=sharing[1080]
https://drive.google.com/file/d/1QHbNaQw51KlTJGMRu0xcCEb7pOAO1oOj/view?usp=sharing[1080]
https://drive.google.com/file/d/1QxeY82IoG7lgMfBBacI0QwPL93p8NQFY/view?usp=sharing[1080]
https://drive.google.com/file/d/1RKa7nKoTwOB1Hb5zT5MtbYKrVOJgNuUu/view?usp=sharing[1080]
https://drive.google.com/file/d/1R9vt4RE69FuNuMZwq8YpF1COz8_wMa-M/view?usp=sharing[1080]
https://drive.google.com/file/d/1R6mb02iGozvmUsBoOVTnQiWKX4cCBc0F/view?usp=sharing[1080]
https://drive.google.com/file/d/1QM7VB_Tk2MOMzAXw1iK9jcpsj9r2gKSe/view?usp=sharing[1080]
https://drive.google.com/file/d/1RDlND51n0iypCR4w8ltb1eL-h02dRI50/view?usp=sharing[1080]
https://drive.google.com/file/d/1RKXSIHZEKKQTUR-x5HFpo9zqTNAFVwGm/view?usp=sharing[1080]
https://drive.google.com/file/d/1QRdAlQJk2driAP15-qDraOPsKySp8XGS/view?usp=sharing[1080]
https://drive.google.com/file/d/1QcnxsVYR7qLlx5T0cLlFUBu_3tS0icDR/view?usp=sharing[1080]
https://drive.google.com/file/d/1RCdZHktVsLYWSvWVDhOwJG7IODzDgOwN/view?usp=sharing[1080]
https://drive.google.com/file/d/1QAUG43hqHeeDgcDuFTNgAOiMjyfGMg5k/view?usp=sharing[1080]
https://drive.google.com/file/d/1QoVGYIi94ToP3BMpHoudyl_m7L4aXciq/view?usp=sharing[1080]
https://drive.google.com/file/d/1QwKNnaZ5Gsjr0OY85dLyuS-342bTl7pg/view?usp=sharing[1080]
https://drive.google.com/file/d/1RLZJc4VXLTXT8sMtvDrKRIaHxAFRXGF0/view?usp=sharing[1080]
https://drive.google.com/file/d/1QQUkG43p40nDf2XyJytR2L1R97H1jjgJ/view?usp=sharing[1080]
https://drive.google.com/file/d/1QRqsaa1xKzEgO3wDCHqzh4VJZilgYNIA/view?usp=sharing[1080]
https://drive.google.com/file/d/1RShIPWzewoo67_y7_SE4W0d7ruvDC9gB/view?usp=sharing[1080]
https://drive.google.com/file/d/1R4PEkfpvuzzygamqWx39ZgYKBd56VR5E/view?usp=sharing[1080]
https://drive.google.com/file/d/1RO3N1GLVKjaobR0Q1p7ekNb41XwRjQol/view?usp=sharing[1080]
https://drive.google.com/file/d/1QWJzfdUxdARpXfs92ewRO0xXXdbx3Ff8/view?usp=sharing[1080]
https://drive.google.com/file/d/1QvzmL9L7H1Lr6jkjpa__R4l4sGoyhBKL/view?usp=sharing[1080]
https://drive.google.com/file/d/1QgmVIe23jGPONvCAep6l9qyGPIGI79f8/view?usp=sharing[1080]
https://drive.google.com/file/d/1ROmKNpcrOa6Y8Uw-ny2m0SvJTKeZfc3y/view?usp=sharing[1080]
https://drive.google.com/file/d/1QH4D2CG7waGUZrA3fBgfnOvcIl2vk3JI/view?usp=sharing[1080]
https://drive.google.com/file/d/1QMt9DOf3wLMk3OGd9d_1JhzrBZJLmaMo/view?usp=sharing[1080]
https://drive.google.com/file/d/1QstMsoj4HeDaFCVvvjhjp8QWf6TTQZuI/view?usp=sharing[1080]
https://drive.google.com/file/d/1QueP18rpPk1h2WI9rBhKRWs0u6ggY-B_/view?usp=sharing[1080]
https://drive.google.com/file/d/1Quw0o6UYsXgmCSTRBppt-3eCimg1ZFsg/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qp2zasNjUmN3ZyB7ukJqj-MNgwtWsbEs/view?usp=sharing[1080]
https://drive.google.com/file/d/1QWk14dilYhu3RKi7XD6U4Sa7YIlBbKvw/view?usp=sharing[1080]
https://drive.google.com/file/d/1QFqevw-9Sbr2tQMrzkIhkMLA1gQFPKS1/view?usp=sharing[1080]
https://drive.google.com/file/d/1RC049fP_4PzzS2QJwh0Aijz5AufZBa-Z/view?usp=sharing[1080]
https://drive.google.com/file/d/1QwJ0vWWG-qf74M6FdKMQ2xfGZ-j-srPj/view?usp=sharing[1080]
https://drive.google.com/file/d/1QoFH7JeDV5HuBAH9ELIw_y_DAs-NRtpj/view?usp=sharing[1080]
https://drive.google.com/file/d/1QjY4klGUsQds1FuKJ8A3PL6nMhO-KPTL/view?usp=sharing[1080]
https://drive.google.com/file/d/1QV_rKy4gyJiY_GO4QgEBFDFV2ixq43Co/view?usp=sharing[1080]
https://drive.google.com/file/d/1QunBTKT0RTpT3IAlYngilQu_FYTWYdF8/view?usp=sharing[1080]
https://drive.google.com/file/d/1RSOVsk4TVcEA714_vxH4YVART5qmLSWR/view?usp=sharing[1080]
https://drive.google.com/file/d/1RPtijA58dy5UC0AEgGZaw6zWHTqT6dxM/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qi42GBCBX89rEZDuQePLnvU3adqTz4sp/view?usp=sharing[1080]
https://drive.google.com/file/d/1QRtbWepaGi7CZDCWqNcHkSCvTwvPJi0z/view?usp=sharing[1080]
https://drive.google.com/file/d/1RAJOJEz5Z4bUweeVQm5UPSvys_WmA1UM/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qdpey2vmWOvGveJ03DhoN1XYRaI1MaDG/view?usp=sharing[1080]
https://drive.google.com/file/d/1QKM8_dNwiBKPl4un39Zwy_BrmL5c9Ug9/view?usp=sharing[1080]
https://drive.google.com/file/d/1RSUgRhujgwumBMIuf9Xktzhi4BHtglW9/view?usp=sharing[1080]
https://drive.google.com/file/d/1QLdKyHaK5gOeBLSii3waWsFnsa0vFZ94/view?usp=sharing[1080]
https://drive.google.com/file/d/1QcKzIXozC0GXZ6cqNCigGONpZAD24VjR/view?usp=sharing[1080]
https://drive.google.com/file/d/1QVvoRyxCj23LnjXtEfhhUmRHIUcpOFu0/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qn05OOMSFK2qO4Klfdt46wANzcPDG39Q/view?usp=sharing[1080]
https://drive.google.com/file/d/1QZJtRzOUc2sMks15T9vXRxAI7qwUrOs-/view?usp=sharing[1080]
https://drive.google.com/file/d/1QivDed4C-rIcFy6OzcgSN2Uohgh7kGMl/view?usp=sharing[1080]
https://drive.google.com/file/d/1QBy08y586Z7nne9kDRV-gEktHd-uYqkj/view?usp=sharing[1080]
https://drive.google.com/file/d/1QcwXqI6iG-K7tF3Q7PVDDPBxGDHh8ZS4/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qseb66k3gybucY9042N8DugCtL9yIpGW/view?usp=sharing[1080]
https://drive.google.com/file/d/1QxKQD4HglnVKSIAmgWHFj7v53oWoPXGl/view?usp=sharing[1080]
https://drive.google.com/file/d/1R3BoiKtjGdrPJgVPMWC7t4DvKAhFJCyD/view?usp=sharing[1080]
https://drive.google.com/file/d/1Q9OMQ7udB-UUvwW1DUh44cBT3lkwaUt2/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qp7GR8Vw_T769P8tzKMg3g1lUn3gFefY/view?usp=sharing[1080]
https://drive.google.com/file/d/1RFL9YaVkM-Wp2AguFaa6Sp9xhQnbCOr1/view?usp=sharing[1080]
https://drive.google.com/file/d/1QelCCp95doEa1JlZc7LwqFYgqeAhlkML/view?usp=sharing[1080]
https://drive.google.com/file/d/1RLU3510KnX_OAOnqh5Fkbdnnb3-Q1aQk/view?usp=sharing[1080]
https://drive.google.com/file/d/1QcE6uqPWW4lW-omJi82Pn1iJkoD6qqnb/view?usp=sharing[1080]
https://drive.google.com/file/d/1QZuiiYBDLGVef3p3CeQ5uzup-2pyJwRd/view?usp=sharing[1080]
https://drive.google.com/file/d/1QDFZyWY74sKp28Y2dbJYSQ8na3T9t2tA/view?usp=sharing[1080]
https://drive.google.com/file/d/1QHmvvfflV2FoPMgK_Urxy0j49qOzQKTm/view?usp=sharing[1080]
https://drive.google.com/file/d/1R8AkkcgQZzdcWo9_fmiGUM6EjufMqNnC/view?usp=sharing[1080]
https://drive.google.com/file/d/1QrjYjCQbnSRqHhVjWDRp7X70-MxlYJDM/view?usp=sharing[1080]
https://drive.google.com/file/d/1R6IVdnSEbBVepLHG0CZIWbvM6bjR-v0T/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qar9gRpKWZyyGDNoBFmIqspKreSmoBUT/view?usp=sharing[1080]
https://drive.google.com/file/d/1QI4bdjxyKCwrNnC3a5KsV-cBIG7UKU9n/view?usp=sharing[1080]
https://drive.google.com/file/d/1RBgm-zIWVDgLXlugyCfQvMzwRu4PrH3O/view?usp=sharing[1080]
https://drive.google.com/file/d/1QR2Jq0QvucxkxsmOIPIIylViKc67UMaB/view?usp=sharing[1080]
https://drive.google.com/file/d/1QQnXMiIQiFaETtU2znADRN6wcMai6aPy/view?usp=sharing[1080]
https://drive.google.com/file/d/1RL_vBIkbDM89Xho7sECgYcItO0qXIBhw/view?usp=sharing[1080]
https://drive.google.com/file/d/1R38p-5nJZc2iyi_76M7nb8lkc4StY8Xt/view?usp=sharing[1080]
https://drive.google.com/file/d/1RTGcOcR1_6CwlKb4vCg029W0KlaBBmll/view?usp=sharing[1080]
https://drive.google.com/file/d/1QIVYMHubV5HdiLWHpmhMkFG3HPehch-F/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qhd5PAhvRBSEobem0eaDJV4TEctl5_1V/view?usp=sharing[1080]
https://drive.google.com/file/d/1QBkawkobBkjzeCJrmvj65EMghPake_6v/view?usp=sharing[1080]
https://drive.google.com/file/d/1QPEcR-uoWSU5-e4Mh3r2ZlHPZgvnAnDX/view?usp=sharing[1080]
https://drive.google.com/file/d/1RAl4QZW7sB4TWhBDAwBkAcU6Nq3hgDDT/view?usp=sharing[1080]
https://drive.google.com/file/d/1QjetH0Orj1VCg6lBs_RPXu4r-Gs-k-rI/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qa9TUqdHdF0d38qU00CL0bw1zr5SIfbH/view?usp=sharing[1080]
https://drive.google.com/file/d/1RIMKE8j4F_-z7ZDgq1-isv3urGsWZ4qy/view?usp=sharing[1080]
https://drive.google.com/file/d/1QPOKhFbi7UWK1wEOkMfEZxTNi6cjm-Au/view?usp=sharing[1080]
https://drive.google.com/file/d/1RH6JpKQp6pVuNHDzJG4CAVfdJsDJm2gN/view?usp=sharing[1080]
https://drive.google.com/file/d/1QbQ2uAWRfzakT8fqzwwCOET85z5586zk/view?usp=sharing[1080]
https://drive.google.com/file/d/1QmpTBF6vFF2tVUzUiIwfO_mv-ZvxySce/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qr1MPUePmFGiKkbgstCcDns47jesu4Xo/view?usp=sharing[1080]
https://drive.google.com/file/d/1RJJ7aYEpbVE3lKodqBk6UrxkNu3dUHU7/view?usp=sharing[1080]
https://drive.google.com/file/d/1QEVnWfoGtoQ29NsxQBcmXKxxvhmwoRFb/view?usp=sharing[1080]
https://drive.google.com/file/d/1RBtMfowpDrIpBiYdimuGw10ILQQGRSkA/view?usp=sharing[1080]
https://drive.google.com/file/d/1QERNgZ5goDcUoL3RZ5ZTW97nGbPqTS8z/view?usp=sharing[1080]
https://drive.google.com/file/d/1R2DT_a5CuNgGfzV3zsXpsqESfxST56lb/view?usp=sharing[1080]
https://drive.google.com/file/d/1RMWv2W8k4wPr0UOjclbsrxzCakyL9luT/view?usp=sharing[1080]
https://drive.google.com/file/d/1R2YDODNETo881rD_DkmgToedXTrGr4b9/view?usp=sharing[1080]
https://drive.google.com/file/d/1RCSNXAyvx5ZZN8rIDyhfJoA5Sfze92Ci/view?usp=sharing[1080]
https://drive.google.com/file/d/1ROpVFg-zRpd5cpAKilDGhTnfv302VjCt/view?usp=sharing[1080]
https://drive.google.com/file/d/1QI_XH6lg8ap_62JDMxqUkDdy_lKTqK5J/view?usp=sharing[1080]
https://drive.google.com/file/d/1RD7dkXjZ-DYfetnFcSC5eVapCVy0GPBa/view?usp=sharing[1080]
https://drive.google.com/file/d/1R0GXnRFpvdGhh7FQBOban2_YoQ50Itn1/view?usp=sharing[1080]
https://drive.google.com/file/d/1RIEbNrZGJ6ZuEypWqkpgEKyoBLMteDKP/view?usp=sharing[1080]
https://drive.google.com/file/d/1QwYqaWvxneEQUQb5JjP1QUb9tpvDPOs3/view?usp=sharing[1080]
https://drive.google.com/file/d/1QE-adFo9lFWbVFUkcI4ePsrc1TlUP5qt/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qs5uRE-Kl8LOe1w7W-iNZeuncoUUeQoy/view?usp=sharing[1080]
https://drive.google.com/file/d/1QhMMcZXllNcXjs7SD5BQK_Xv9S9G6oui/view?usp=sharing[1080]
https://drive.google.com/file/d/1ROkrBt6GoOCtUz3Qf_sn7MBpYCiDDga0/view?usp=sharing[1080]
https://drive.google.com/file/d/1QCocsseC0QcCBWfFqk2Z4NbS0q6G_GB1/view?usp=sharing[1080]
https://drive.google.com/file/d/1QX6XZe2eOC1CdtpqRmugz4qrNJQigqEq/view?usp=sharing[1080]
https://drive.google.com/file/d/1QAObET2nDxq87GQAJsPaWWH4_nt0IUmR/view?usp=sharing[1080]
https://drive.google.com/file/d/1RHNJRVbRUxqx7nwQHjM3JB_I02Caz9gp/view?usp=sharing[1080]
https://drive.google.com/file/d/1RE-NJlSTOF0TjiZK-MuCGLBWf_rXoGZZ/view?usp=sharing[1080]
https://drive.google.com/file/d/1RLimOXfqgAqk2yFP5q5XqHKHSaNpoh5N/view?usp=sharing[1080]
https://drive.google.com/file/d/1RRe5EsSnnulSgn2amAUTg97Eb6-vB4Zn/view?usp=sharing[1080]
https://drive.google.com/file/d/1QkaP4I4VjlrQKDOSjnL4Mq18JkJFDBDU/view?usp=sharing[1080]
https://drive.google.com/file/d/1QQwFJqsrT74C3DFDgd3r5Daq_ZhnP3s_/view?usp=sharing[1080]
https://drive.google.com/file/d/1RF-f5nsmPe3SY8n-EZ4akThiZvhOcWIu/view?usp=sharing[1080]
https://drive.google.com/file/d/1RHWYUvIWmFqx01FvhaUlfsDxfs96YSyt/view?usp=sharing[1080]
https://drive.google.com/file/d/1R7gm4QD4eULkMbfWdxEQU2bFpHb_Dvkt/view?usp=sharing[1080]
https://drive.google.com/file/d/1QhRHEUljJ57DBx-EF2Jg_Zv7MbF3zr8k/view?usp=sharing[1080]
https://drive.google.com/file/d/1RAB102n3lLRsN2h2unFuf93ek_ot7UBY/view?usp=sharing[1080]
https://drive.google.com/file/d/1QssT8aIeqto7A3MdTzl4KPVHynwZy2ZX/view?usp=sharing[1080]
https://drive.google.com/file/d/1QrYfYrfZGsKarSfwhXUznrOGpvRSUc3K/view?usp=sharing[1080]
https://drive.google.com/file/d/1QeayTPOmDQZ1AuEeZX4i8VazMVut2NPI/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qw1WFpPXyPl8fSzp9vkfwdsEMYlSQaOu/view?usp=sharing[1080]
https://drive.google.com/file/d/1QQUA0vooCwNZ12GfK9HvweA_O-EfEyLf/view?usp=sharing[1080]
https://drive.google.com/file/d/1RQUqRs-2BB1zgh6t_wJVyN-E9NIfhQEB/view?usp=sharing[1080]
https://drive.google.com/file/d/1R0p8S8hpH-MfotWt9C2atABl1WQLbYLv/view?usp=sharing[1080]
https://drive.google.com/file/d/1QGMtNOMN5M9s2aB09h6jKvBf_EZsTi7g/view?usp=sharing[1080]
https://drive.google.com/file/d/1QY3HomsHkIRGOqn_X6hRye918rWopPJ3/view?usp=sharing[1080]
https://drive.google.com/file/d/1QeHAXa-gImUuZ9pfbfxdXdWOMTaN8fgH/view?usp=sharing[1080]
https://drive.google.com/file/d/1RN-qbRjf15wwS0nYETHFGH66lwFG5WPV/view?usp=sharing[1080]
https://drive.google.com/file/d/1RKPnARmmXFBe_BCsWO6ljxuytZBUReby/view?usp=sharing[1080]
https://drive.google.com/file/d/1QGNLNJD1a3YqCS8dUZS2NrXH78IcBrsH/view?usp=sharing[1080]
https://drive.google.com/file/d/1RL-5tzFlfAdB-IaImG0pCercZfzKQAug/view?usp=sharing[1080]
https://drive.google.com/file/d/1RMtz9YyHh-_G7T2EtZ2-vwAijYLeDmjJ/view?usp=sharing[1080]
https://drive.google.com/file/d/1RJE2aUM7rJ9wIM6drqPLODoyCa0wELuF/view?usp=sharing[1080]
https://drive.google.com/file/d/1QkkEf550BL_OVyZVHxkpqqYd936vJIeB/view?usp=sharing[1080]
https://drive.google.com/file/d/1QN2UuHnluw9y7QOpuTqwJ5qhVJPWBKZ0/view?usp=sharing[1080]
https://drive.google.com/file/d/1R3VY3A0C2LC7ujkUr1_kOF4bEZSMzhFC/view?usp=sharing[1080]
https://drive.google.com/file/d/1RHSDeQQz8jxd0JleCBg5mwJnmswztgRb/view?usp=sharing[1080]
https://drive.google.com/file/d/1QUWW1nD9zCcvRkmwRaO_Feb1nRqi1osz/view?usp=sharing[1080]
https://drive.google.com/file/d/1QvDguUXN22cXHkDKd0q7uKyQAMEwS-Ip/view?usp=sharing[1080]
https://drive.google.com/file/d/1RGH75S_cHQzDbEGoLjzEFe0dQZKqRF_P/view?usp=sharing[1080]
https://drive.google.com/file/d/1QPl27lzuVzm7Gh985MDVjjO4Mgc0aMEU/view?usp=sharing[1080]
https://drive.google.com/file/d/1RIjKDn_3brigeNktMFCl5izPQLaKu_5j/view?usp=sharing[1080]
https://drive.google.com/file/d/1QGJrIU88PAB71NrvHT1UBpLTar62hRm3/view?usp=sharing[1080]
https://drive.google.com/file/d/1RK0SMQVMh89gCoAhn4ea4hQlOQUDlDMk/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qv3qVQb6eyNEdsXSEgAYM01Ijzd8wC9J/view?usp=sharing[1080]
https://drive.google.com/file/d/1QFMqVsE5MAl2X9b5WD9Y2ceKpL1UKVGR/view?usp=sharing[1080]
https://drive.google.com/file/d/1QxxgVTwNbVXLFJL2tErjGJWfQ-zo_7qg/view?usp=sharing[1080]
https://drive.google.com/file/d/1RJHJrtqv4gD52CqY4azuwYW8ZVViwZ8J/view?usp=sharing[1080]
https://drive.google.com/file/d/1QJxOrRrVsjsHHJ-VvEUHdoqJhNNfD2MD/view?usp=sharing[1080]
https://drive.google.com/file/d/1RHIO3VEF1_i-7K4G8M4jh2HcHhC9woZZ/view?usp=sharing[1080]
https://drive.google.com/file/d/1QaHP1J1BI9ZnulKRiQvpXkvzKgzByiPE/view?usp=sharing[1080]
https://drive.google.com/file/d/1QJYyAT9ZZQJHVh3LQitqmBYWGfd88kr_/view?usp=sharing[1080]
https://drive.google.com/file/d/1R8jv-IA45m0jGfON2nHS5QZz9_nuzQzi/view?usp=sharing[1080]
https://drive.google.com/file/d/1QezjNBYBFNxMZdJ6xcwnJw7oNoyJkmBJ/view?usp=sharing[1080]
https://drive.google.com/file/d/1QqcbrR-T8aN8ZDGh_MUqxVGmk9N5KRHD/view?usp=sharing[1080]
https://drive.google.com/file/d/1R9ZRghjUyY-jWg9TEjDhcasvawqTJRkF/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qc9WkXFp9NV6ZHJ1QLqJAy4Uyt0CSBds/view?usp=sharing[1080]
https://drive.google.com/file/d/1QEQCsUEPGGBBHdLYTvjZqbJnXSSFYeGx/view?usp=sharing[1080]
https://drive.google.com/file/d/1Q9us7fnTbC8QG8SNRbhPNVTDB9dTQYLm/view?usp=sharing[1080]
https://drive.google.com/file/d/1QXY6Bx5nyTL_GM3Ma4L6MQ7n6rwOD16z/view?usp=sharing[1080]
https://drive.google.com/file/d/1QDq9md1_cDDA_0tkvX0GknUsmM2kUt4Y/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qn4GFAntTe7KoMNAsFbH1yFrYxWN4MSK/view?usp=sharing[1080]
https://drive.google.com/file/d/1QqpQ9syEUmbTtnH-tnu59Zql9wgAPOkV/view?usp=sharing[1080]
https://drive.google.com/file/d/1QWdby-3lCp1nOUhqecJNMEhTlxuapp87/view?usp=sharing[1080]
https://drive.google.com/file/d/1QI-REcoNyvhr2WyeiXmnLpyefrNJZu3x/view?usp=sharing[1080]
https://drive.google.com/file/d/1RNQaUFHjNc0lDv3u2C2a5vKikdXO1xYg/view?usp=sharing[1080]
https://drive.google.com/file/d/1RMi53W-xM5q73bskkLDGGUoUt2Pdu9bZ/view?usp=sharing[1080]
https://drive.google.com/file/d/1QaTxE0laILtlVfB8rHfokskKurovOTul/view?usp=sharing[1080]
https://drive.google.com/file/d/1QUYU8PSfOhZLvzpYDK7AZs5Y99l_dqpA/view?usp=sharing[1080]
https://drive.google.com/file/d/1Qy6i04dHoe4IpZVgIT8Kw86rqojh1uUt/view?usp=sharing[1080]







== 1st Quarter
=== Module 1 -- Review 1
==== Week 1
//tag::Week-1[]
//tag::Weekly-Overview-1[]
July 22-26

There is no "Launch Work."
//end::Weekly-Overview-1[]
//end::Week-1[]

==== Week 2
//tag::Week-2
//tag::Weekly-Overview-2[]
July 29-Aug 2

There is no "Launch Work."
//end::Weekly-Overview-2[]
//end::Week-2[]

==== Week 3
//tag::Week-3[]
Chapters 1-7

//tag::Weekly-Overview-3[]
Aug 5-9

We will start learning the Hebrew aphabet as well as some words.

//end::Weekly-Overview-3[]
//tag::Assignment-001[]
===== Monday, August 5, 2024
No work

//end::Assignment-001[]
//tag::Assignment-002[]
===== Tuesday, August 6, 2024
We covered the syllabus and discussed homework for the week.

We watched the first Aleph with Beth video.

We covered aleph through vav.

//end::Assignment-002[]
//tag::Assignment-003[]
===== Wednesday, August 7, 2024

Review aleph through vav.

Watch {lesson1video}

Watch {lesson2video}

//end::Assignment-003[]
//tag::Assignment-004[]
===== Thursday, August 8, 2024

Review aleph through vav.

Watch {lesson1video}

Watch {lesson2video}

//end::Assignment-004[]
//tag::Assignment-005[]
===== Friday, August 9, 2024

//end::Assignment-005[]

//end::Week-3[]


==== Week 4
//tag::Week-4[]
Chapters 8-12

//tag::Weekly-Overview-4[]
We will reinforce the letters we have learned by learning some vocabulary. We will introduce vowels and syllables.

//end::Weekly-Overview-4[]
//tag::Assignment-006[]
===== Monday, August 12, 2024
Study the Hebrew Consonants.

If the links do not work, try right-clicking them and opening them in a new tab.

https://drive.google.com/file/d/1IfoRKLxtd76SrZtIBSmlldhIUZ-nMkjh/view?usp=share_link[Writing Hebrew Consonants]

Watch {lesson1-2video}


Optional

Watch {lesson1video}

Watch {lesson2video}


//end::Assignment-006[]
//tag::Quiz-01[]
Study the Hebrew Consonants

https://drive.google.com/file/d/1IfoRKLxtd76SrZtIBSmlldhIUZ-nMkjh/view?usp=share_link[Writing Hebrew Consonants]

//end::Quiz-01[]
//tag::Assignment-007[]
===== Tuesday, August 13, 2024
We will practice writing and saying words from the videos. We will very briefly talk about vowels. 

//end::Assignment-007[]
//tag::Assignment-008[]
===== Wednesday, August 14, 2024
https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Review Vocabulary for chapters 1-3]

Watch {lesson1-2video}

Watch {lesson3video}

Watch {lesson3bvideo}

//end::Assignment-008[]
//tag::Assignment-009[]
===== Thursday, August 15, 2024
https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Review Vocabulary for chapters 1-3]

Watch {lesson1-2video}

Watch {lesson3video}

Watch {lesson3bvideo}

//end::Assignment-009[]
//tag::Assignment-010[]
===== Friday, August 16, 2024
We will begin discussing syllables.

We will also try to watch the lesson 4 videos and disccus them.


//end::Assignment-010[]
//tag::Quiz-02[]
Quiz over just the vocabulary from lessons 1 and 2.
https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Vocabulary for chapters 1-3]

//end::Quiz-02[]
//end::Week-4[]

==== Week 5
//tag::Week-5[]


//tag::Weekly-Overview-5[]
We will continue to discuss vowels and syllables as we learn more vocabulary. 

We will also start learning pronouns. 

//end::Weekly-Overview-5[]

//tag::Assignment-011[]
===== Monday, August 19, 2024
Read through these lessons.

https://hebrew.billmounce.com/BasicsBiblicalHebrew-02.pdf[Lesson on Vowels]

https://hebrew.billmounce.com/BasicsBiblicalHebrew-03.pdf[Lesson on Syllables]

Watch {lesson3video}

Watch {lesson3bvideo}

//end::Assignment-011[]
//tag::Assignment-012[]
===== Tuesday, August 20, 2024
We will continue reviewing the vocabulary from lessons 1-3 and syllables.

We will talk about the conjuction and dagheshes.


//end::Assignment-012[]
//tag::Assignment-013[]
===== Wednesday, August 21, 2024

https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Vocabulary for chapters 1-3]

Watch {lesson1video}

Watch {lesson2video}

Watch {lesson1-2video}

//end::Assignment-013[]
//tag::Assignment-014[]
===== Thursday, August 22, 2024

https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Vocabulary for chapters 1-3]

Watch {lesson3video}

Watch {lesson3bvideo}

//end::Assignment-014[]
//tag::Assignment-015[]
===== Friday, August 23, 2024
We will start going over 
https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

//end::Assignment-015[]
//tag::Quiz-03[]
Quiz over Vocabulary for chapters 1-3 and syllables.

//end::Quiz-03[]
//end::Week-5[]


==== Week 6
//tag::Week-6[]
Chaptes 1-17

We will discuss verb endings and pronouns.

//tag::Weekly-Overview-6[]
We will learn about construct forms.

//end::Weekly-Overview-6[]
//tag::Assignment-016[]
===== Monday, August 26, 2024
Review the lesson 4 vocabulary. https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

Watch {lesson4video}

Watch {lesson4bvideo}

Watch {lesson5video}

//end::Assignment-016[]
//tag::Assignment-017[]
===== Tuesday, August 27, 2024
We will go over the lesson 5 vocabulary. https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

//end::Assignment-017[]
//tag::Assignment-018[]
===== Wednesday, August 28, 2024
Review Vocabulary from chapters 4-5. https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

Watch {lesson5video}

Watch {lesson5bvideo}

//end::Assignment-018[]
//tag::Assignment-019[]
===== Thursday, August 29, 2024
Review Vocabulary from chapters 4-5. https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

Watch {lesson5video}

Watch {lesson5bvideo}

//end::Assignment-019[]
//tag::Assignment-020[]
===== Friday, August 30, 2024
We translated some sentences and started lesson 8.

//end::Assignment-020[]
//tag::Quiz-04[]
Quiz over the vocabulary from lessons 4 and 5.

//end::Quiz-04[]
//end::Week-6[]

==== Week 7
//tag::Week-7[]

//tag::Weekly-Overview-7[]
We will take our first test.

//end::Weekly-Overview-7[]
//tag::Assignment-021[]
===== Monday, September 2, 2024
*Labor Day*

//end::Assignment-021[]
//tag::Assignment-022[]
===== Tuesday, September 3, 2024
*Satellite Day*

Watch {lesson4video}

Watch {lesson4bvideo}

Watch {lesson5video}

Watch {lesson5bvideo}

Watch {lesson6video}

Review Vocabulary from chapters 1-6. https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Vocabulary for chapters 1-3]
https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

Optional:

Watch {lesson1video}, {lesson2video}, {lesson3video}, {lesson3bvideo}, 


//end::Assignment-022[]
//tag::Assignment-023[]
===== Wednesday, September 4, 2024
Review Vocabulary from chapters 1-6. https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Vocabulary for chapters 1-3]
https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

Watch {lesson1-2video}

Watch {lesson3-4video}

Watch {lesson6video}

Optional:

Watch {lesson1video}, {lesson2video}, {lesson3video}, {lesson3bvideo}, {lesson4video}, {lesson4bvideo}, {lesson5video}, {lesson5bvideo}


//end::Assignment-023[]
//tag::Assignment-024[]
===== Thursday, September 5, 2024
Review Vocabulary from chapters 1-6. https://drive.google.com/file/d/1RWsfP1sF9S6lsDRup889oAOnXsYWkfZM/view?usp=share_link[Vocabulary for chapters 1-3]
https://drive.google.com/file/d/1RYIx2s1g7IKt02ww6nyNZcIf-ToMexbp/view?usp=share_link[Vocabulary for Chapters 4-6]

Watch {lesson6video}

Watch {lesson5-6video}

Optional:

Watch {lesson1video}, {lesson2video}, {lesson3video}, {lesson3bvideo}, {lesson4video}, {lesson4bvideo}, {lesson5video}, {lesson5bvideo}


//end::Assignment-024[]
//tag::Assignment-025[]
===== Friday, September 6, 2024

//end::Assignment-025[]
//tag::Test-01[]
This will cover vocabulary from lessons 1-6.

//end::Test-01[]
//end::Week-7[]

=== Module 2 -- Review 2
==== Week 8
//tag::Week-8[]
Chapters 18-21

//tag::Weekly-Overview-8[]
We will focus on learning new vocabulary and reading some phrases.


//end::Weekly-Overview-8[]
//tag::Assignment-026[]
===== Monday, September 9, 2024
Watch {lesson7video}, {lesson8video}, and {lesson8bvideo}.

Study {lesson7-10vocabulary}

//end::Assignment-026[]
//tag::Assignment-027[]
===== Tuesday, September 10, 2024

//end::Assignment-027[]
//tag::Assignment-028[]
===== Wednesday, September 11, 2024
Watch {lesson8video}, {lesson8bvideo}, and {lesson7-8video}.

Study {lesson7-10vocabulary}

//end::Assignment-028[]
//tag::Assignment-029[]
===== Thursday, September 12, 2024
Watch {lesson7-8video}, {lesson9video}, and {lesson10video}

Study {lesson7-10vocabulary}

//end::Assignment-029[]
//tag::Assignment-030[]
===== Friday, September 13, 2024


//end::Assignment-030[]
//tag::Quiz-05[]
Quiz over the voacabulary for lessons 7-10.

//end::Quiz-05[]
//end::Week-8[]


==== Week 9
//tag::Week-9[]
Chapters 22-27

//tag::Weekly-Overview-9[]
We will learn more vocabulary and review construct forms. 

//end::Weekly-Overview-9[]
//tag::Assignment-031[]
===== Monday, September 16, 2024
Watch {lesson9-10video}, {lesson11video}, and {lesson11bvideo}

Study {lesson11-12vocabulary}

//end::Assignment-031[]
//tag::Assignment-032[]
===== Tuesday, September 17, 2024
*Chapel Day*

We will talk more about contruct forms.

//end::Assignment-032[]
//tag::Assignment-033[]
===== Wednesday, September 18, 2024
Watch {lesson12video} and {lesson12bvideo}

Study {lesson11-12vocabulary}

//end::Assignment-033[]
//tag::Assignment-034[]
===== Thursday, September 19, 2024
Watch {lesson9-10video} and {lesson11-12video}

Study {lesson11-12vocabulary}

Optional:

Watch {lesson12video} and {lesson12bvideo}

//end::Assignment-034[]
//tag::Assignment-035[]
===== Friday, September 20, 2024

//end::Assignment-035[]
//tag::Quiz-06[]
Quiz over the vocabulary for lessons 11-12.

//end::Quiz-06[]
//end::Week-9[]

==== Week 10
//tag::Week-10[]
Chapters 18-27

//tag::Weekly-Overview-10[]
10

//end::Weekly-Overview-10[]
//end::Week-10[]

==== Week 11
//tag::Week-11[]
//tag::Weekly-Overview-11[]
11

//end::Weekly-Overview-11[]
//tag::Assignment-036[]
===== Monday, September 30, 2024
Review {lesson7-10vocabulary} and {lesson11-12vocabulary}

//end::Assignment-036[]
//tag::Assignment-037[]
===== Tuesday, October 1, 2024

//end::Assignment-037[]
//tag::Assignment-038[]
===== Wednesday, October 2, 2024
As needed review {lesson7-10vocabulary}, {lesson11-12vocabulary}, {lesson7video}, {lesson7bvideo}, {lesson8video}, {lesson8bvideo}, {lesson7-8video}, {lesson9video}, {lesson10video}, {lesson9-10video}, {lesson11video}, {lesson11bvideo}, {lesson12video}, {lesson12bvideo}, and {lesson11-12video}

//end::Assignment-038[]
//tag::Assignment-039[]
===== Thursday, October 3, 2024
As needed review {lesson7-10vocabulary}, {lesson11-12vocabulary}, {lesson7video}, {lesson7bvideo}, {lesson8video}, {lesson8bvideo}, {lesson7-8video}, {lesson9video}, {lesson10video}, {lesson9-10video}, {lesson11video}, {lesson11bvideo}, {lesson12video}, {lesson12bvideo}, and {lesson11-12video}

//end::Assignment-039[]
//tag::Assignment-040[]
===== Friday, October 4, 2024

//end::Assignment-040[]
//tag::Test-02[]
Test over the vocabulary for lessons 7-12.

//end::Test-02[]

//end::Week-11[]


== 2nd Quarter
=== Module 3 -- Chapters 28-30

==== Week 12
//tag::Week-12[]
//tag::Weekly-Overview-12[]
We will continue learning vocabulary 

//end::Weekly-Overview-12[]

//tag::Assignment-041[]
===== Monday, October 7, 2024
Watch
{lesson13video}
//end::Assignment-041[]
//tag::Assignment-042[]
===== Tuesday, October 8, 2024
We will review {lesson13-14vocabulary} and {lesson13-14script}

//end::Assignment-042[]
//tag::Assignment-043[]
===== Wednesday, October 9, 2024
Watch {lesson14video} and {lesson13-14video}

Study {lesson13-14vocabulary}

//end::Assignment-043[]
//tag::Assignment-044[]
===== Thursday, October 10, 2024
Watch {lesson14video} and {lesson13-14video}

Study {lesson13-14vocabulary}

//end::Assignment-044[]
//tag::Assignment-045[]
===== Friday, October 11, 2024

//end::Assignment-045[]
//tag::Quiz-07[]
Quiz over chatper 14 vocabulary

//end::Quiz-07[]
//end::Week-12[]

==== Week 13
//tag::Week-13[]
//tag::Weekly-Overview-13[]
13

//end::Weekly-Overview-13[]
//tag::Assignment-046[]
===== Monday, October 14, 2024

Watch {lesson13-14video} and {lesson15video}

//end::Assignment-046[]
//tag::Assignment-047[]
===== Tuesday, October 15, 2024

//end::Assignment-047[]
//tag::Assignment-048[]
===== Wednesday, October 16, 2024
Watch {lesson15video} and {lesson14video}

Study https://drive.google.com/file/d/12uDhPWY-kliD4H0xbrka0LkBUXqqaJbb/view?usp=share_link[Lesson 15 Vocabulary] and https://drive.google.com/file/d/12r_037kErWMSChkEtQ3F2ESDTjJ8MNLL/view?usp=sharing[Lesson 15 Script]

//end::Assignment-048[]
//tag::Assignment-049[]
===== Thursday, October 17, 2024
Watch {lesson16video}
Study https://drive.google.com/file/d/12uDhPWY-kliD4H0xbrka0LkBUXqqaJbb/view?usp=share_link[Lesson 15 Vocabulary] and https://drive.google.com/file/d/12r_037kErWMSChkEtQ3F2ESDTjJ8MNLL/view?usp=sharing[Lesson 15 Script]

//end::Assignment-049[]
//tag::Assignment-050[]
===== Friday, October 18, 2024

//end::Assignment-050[]
//tag::Quiz-08[]
Lesson 15 Vocabulary quiz

//end::Quiz-08[]
//end::Week-13[]

==== Week 14
//tag::Week-14[]
//tag::Weekly-Overview-14[]
14

//end::Weekly-Overview-14[]
//tag::Assignment-051[]
===== Monday, October 21, 2024
Watch {lesson17video}

Study https://drive.google.com/file/d/13UJ4Do7UTLi31wN_ktXlWggoQJD2qCSz/view?usp=share_link[Lesson 17 Script] and https://drive.google.com/file/d/13VwilJCgc62WCJ_9GjLD9i5kaoDIcB76/view?usp=sharing[Lesson 17 Vocabulary]

//end::Assignment-051[]
//tag::Assignment-052[]
===== Tuesday, October 22, 2024
*Seminar Day*

//end::Assignment-052[]
//tag::Assignment-053[]
===== Wednesday, October 23, 2024

Watch {lesson14-15video}

Study https://drive.google.com/file/d/13UJ4Do7UTLi31wN_ktXlWggoQJD2qCSz/view?usp=share_link[Lesson 17 Script] and https://drive.google.com/file/d/13VwilJCgc62WCJ_9GjLD9i5kaoDIcB76/view?usp=sharing[Lesson 17 Vocabulary]

https://hebrew.billmounce.com/BasicsBiblicalHebrew-09.pdf[Bill Mounce - Basics of Biblical Hebrew]

https://freehebrew.online/resources/[Aleph with Beth's online resources]

//end::Assignment-053[]
//tag::Assignment-054[]
===== Thursday, October 24, 2024

Watch {lesson16video} and {lesson17video}

Study https://drive.google.com/file/d/13UJ4Do7UTLi31wN_ktXlWggoQJD2qCSz/view?usp=share_link[Lesson 17 Script] and https://drive.google.com/file/d/13VwilJCgc62WCJ_9GjLD9i5kaoDIcB76/view?usp=sharing[Lesson 17 Vocabulary]

//end::Assignment-054[]
//tag::Assignment-055[]
===== Friday, October 25, 2024

//end::Assignment-055[]
//tag::Quiz-09[]
We will have a quiz over the vocabulary for chapter 17.

//end::Quiz-09[]
//end::Week-14[]


==== Week 15
//tag::Week-15[]
//tag::Weekly-Overview-15[]
We will continue learning vocabulary.


//end::Weekly-Overview-15[]

//tag::Assignment-056[]
===== Monday, October 28, 2024
Watch {lesson18video} and {lesson17-18video}.

Study https://docs.google.com/document/d/12vvtbv2yEH0ttkCEYv4oK0rfPR-FgrfB/edit?usp=share_link&rtpof=true&sd=true[Lessons 18 and 19 Vocabulary]

Study https://docs.google.com/document/d/139Zk1BJwEU4wq9PbZHXjGi-ZEUs9Zr7f/edit?usp=share_link&ouid=112551519005771291326&rtpof=true&sd=true[Lesson 18 Script]

Study https://docs.google.com/document/d/13BXNmujyo8X2_YbJMUFexwFW5yTTAAen/edit?usp=sharing&ouid=112551519005771291326&rtpof=true&sd=true[Lesson 19 Script]

//end::Assignment-056[]
//tag::Assignment-057[]
===== Tuesday, October 29, 2024

//end::Assignment-057[]
//tag::Assignment-058[]
===== Wednesday, October 30, 2024
Watch {lesson19video}.

Study https://docs.google.com/document/d/12vvtbv2yEH0ttkCEYv4oK0rfPR-FgrfB/edit?usp=share_link&rtpof=true&sd=true[Lessons 18 and 19 Vocabulary]

Study https://docs.google.com/document/d/139Zk1BJwEU4wq9PbZHXjGi-ZEUs9Zr7f/edit?usp=share_link&ouid=112551519005771291326&rtpof=true&sd=true[Lesson 18 Script]

Study https://docs.google.com/document/d/13BXNmujyo8X2_YbJMUFexwFW5yTTAAen/edit?usp=sharing&ouid=112551519005771291326&rtpof=true&sd=true[Lesson 19 Script]

//end::Assignment-058[]
//tag::Assignment-059[]
===== Thursday, October 31, 2024
Watch {lesson19video}.

Study https://docs.google.com/document/d/12vvtbv2yEH0ttkCEYv4oK0rfPR-FgrfB/edit?usp=share_link&rtpof=true&sd=true[Lessons 18 and 19 Vocabulary]

Study https://docs.google.com/document/d/139Zk1BJwEU4wq9PbZHXjGi-ZEUs9Zr7f/edit?usp=share_link&ouid=112551519005771291326&rtpof=true&sd=true[Lesson 18 Script]

Study https://docs.google.com/document/d/13BXNmujyo8X2_YbJMUFexwFW5yTTAAen/edit?usp=sharing&ouid=112551519005771291326&rtpof=true&sd=true[Lesson 19 Script]

//end::Assignment-059[]
//tag::Assignment-060[]
===== Friday, November 1, 2024

//end::Assignment-060[]
//tag::Quiz-10[]
Quiz 10

//end::Quiz-10[]
//end::Week-15[]

==== Week 16
//tag::Week-16[]
//tag::Weekly-Overview-16[]
16

//end::Weekly-Overview-16[]

//tag::Assignment-061[]
===== Monday, November 4, 2024
Review 
https://drive.google.com/open?id=16peTjCV2KWwktsuw_3btl83jPbCqo7Cj&usp=drive_fs[Lesson 1-20 Vocabulary]


//end::Assignment-061[]
//tag::Assignment-062[]
===== Tuesday, November 5, 2024
*Satellite Day*

Review 
https://drive.google.com/open?id=16peTjCV2KWwktsuw_3btl83jPbCqo7Cj&usp=drive_fs[Lesson 1-20 Vocabulary]

//end::Assignment-062[]
//tag::Assignment-063[]
===== Wednesday, November 6, 2024

Review 
https://drive.google.com/open?id=16peTjCV2KWwktsuw_3btl83jPbCqo7Cj&usp=drive_fs[Lesson 1-20 Vocabulary]

//end::Assignment-063[]
//tag::Assignment-064[]
===== Thursday, November 7, 2024

Review 
https://drive.google.com/open?id=16peTjCV2KWwktsuw_3btl83jPbCqo7Cj&usp=drive_fs[Lesson 1-20 Vocabulary]

//end::Assignment-064[]
//tag::Assignment-065[]
===== Friday, November 8, 2024

//end::Assignment-065[]
//tag::Test-03[]
Test over 
https://drive.google.com/open?id=16peTjCV2KWwktsuw_3btl83jPbCqo7Cj&usp=drive_fs[Lesson 1-20 Vocabulary]

//end::Test-03[]
//end::Week-16[]


=== Module 4 -- Chapters 31-32

==== Week 17
//tag::Week-17[]
//tag::Weekly-Overview-17[]
17

//end::Weekly-Overview-17[]

//tag::Assignment-066[]
===== Monday, November 11, 2024

Watch {lesson21video}

Study 
https://drive.google.com/open?id=17zEW36iJPE_Chybp9kKMYInWyC4_yn34&usp=drive_fs[Lesson 21 Vocabulary]

Review
https://drive.google.com/open?id=17yvLA7c-MpFNs_mUMaI8LtCVReqfmBNy&usp=drive_fs[Lesson 21 Script]

//end::Assignment-066[]
//tag::Assignment-067[]
===== Tuesday, November 12, 2024

//end::Assignment-067[]
//tag::Assignment-068[]
===== Wednesday, November 13, 2024

Watch {lesson21video}

Review older lessons.

Study 
https://drive.google.com/open?id=17zEW36iJPE_Chybp9kKMYInWyC4_yn34&usp=drive_fs[Lesson 21 Vocabulary]

Review
https://drive.google.com/open?id=17yvLA7c-MpFNs_mUMaI8LtCVReqfmBNy&usp=drive_fs[Lesson 21 Script]


//end::Assignment-068[]
//tag::Assignment-069[]
===== Thursday, November 14, 2024

Watch {lesson21video}

Review older lessons.

Study 
https://drive.google.com/open?id=17zEW36iJPE_Chybp9kKMYInWyC4_yn34&usp=drive_fs[Lesson 21 Vocabulary]

Review
https://drive.google.com/open?id=17yvLA7c-MpFNs_mUMaI8LtCVReqfmBNy&usp=drive_fs[Lesson 21 Script]

//end::Assignment-069[]
//tag::Assignment-070[]
===== Friday, November 15, 2024

//end::Assignment-070[]
//tag::Quiz-11[]
Quiz over lesson 21 vocabulary.

//end::Quiz-11[]
//end::Week-17[]

==== Week 18
//tag::Week-18[]
//tag::Weekly-Overview-18[]
18

//end::Weekly-Overview-18[]

//tag::Assignment-071[]
===== Monday, November 18, 2024

Review the lesson 22 video.

https://drive.google.com/file/d/19iK2ZexPFfy6H84hP2VgTRrkVK4j7I36/view?usp=sharing[Vocabulary]

https://drive.google.com/file/d/19huz-a8jS-1DmMrwfnxC5tcJ8Muzb_yg/view?usp=sharing[Script]

//end::Assignment-071[]
//tag::Assignment-072[]
===== Tuesday, November 19, 2024
*Chapel Day*

//end::Assignment-072[]
//tag::Assignment-073[]
===== Wednesday, November 20, 2024

Review the lesson 22 video.

https://drive.google.com/file/d/19iK2ZexPFfy6H84hP2VgTRrkVK4j7I36/view?usp=sharing[Vocabulary]

https://drive.google.com/file/d/19huz-a8jS-1DmMrwfnxC5tcJ8Muzb_yg/view?usp=sharing[Script]


//end::Assignment-073[]
//tag::Assignment-074[]
===== Thursday, November 21, 2024

Review the lesson 22 video.

https://drive.google.com/file/d/19iK2ZexPFfy6H84hP2VgTRrkVK4j7I36/view?usp=sharing[Vocabulary]

https://drive.google.com/file/d/19huz-a8jS-1DmMrwfnxC5tcJ8Muzb_yg/view?usp=sharing[Script]


//end::Assignment-074[]
//tag::Assignment-075[]
===== Friday, November 22, 2024

//end::Assignment-075[]
//tag::Quiz-12[]
Quiz 12

//end::Quiz-12[]
//end::Week-18[]

==== Week 19
//tag::Week-19[]
//tag::Weekly-Overview-19[]
19

//end::Weekly-Overview-19[]
//end::Week-19[]

==== Week 20
//tag::Week-20[]
//tag::Weekly-Overview-20[]
20

//end::Weekly-Overview-20[]

//tag::Assignment-076[]
===== Monday, December 2, 2024

//end::Assignment-076[]
//tag::Assignment-077[]
===== Tuesday, December 3, 2024
*Seminar Day*

//end::Assignment-077[]
//tag::Assignment-078[]
===== Wednesday, December 4, 2024

//end::Assignment-078[]
//tag::Assignment-079[]
===== Thursday, December 5, 2024

//end::Assignment-079[]
//tag::Assignment-080[]
===== Friday, December 6, 2024

//end::Assignment-080[]
//tag::Quiz-13[]
Quiz 13

//end::Quiz-13[]
//end::Week-20[]

==== Week 21
//tag::Week-21[]
//tag::Weekly-Overview-21[]
21

//end::Weekly-Overview-21[]

//tag::Assignment-081[]
===== Monday, December 9, 2024

//end::Assignment-081[]
//tag::Assignment-082[]
===== Tuesday, December 10, 2024

//end::Assignment-082[]
//tag::Assignment-083[]
===== Wednesday, December 11, 2024

//end::Assignment-083[]
//tag::Assignment-084[]
===== Thursday, December 12, 2024

//end::Assignment-084[]
//tag::Assignment-085[]
===== Friday, December 13, 2024
*Last Day of School*

//end::Assignment-085[]
//tag::Test-04[]
Test 4

//end::Test-04[]
//end::Week-21[]







== 3rd Quarter
=== Module 5 -- Chapters 33-34
==== Week 22
//tag::Week-22[]
22

//tag::Weekly-Overview-22[]


//end::Weekly-Overview-22[]
//tag::Assignment-086[]
===== Monday, December 30, 2024
*Holiday*

//end::Assignment-086[]
//tag::Assignment-087[]
===== Tuesday, December 31, 2024
*Holiday*

//end::Assignment-087[]
//tag::Assignment-088[]
===== Wednesday, January 1, 2024
*Holiday*
 
//end::Assignment-088[]
//tag::Assignment-089[]
===== Thursday, January 2, 2024
*Satellite Day*

//end::Assignment-089[]
//tag::Assignment-090[]
===== Friday, January 3, 2024
*Satellite Day*

//end::Assignment-090[]
//end::Week-22[]
Review Chapters 13-17


==== Week 23
//tag::Week-23[]
//tag::Weekly-Overview-23[]
23

//end::Weekly-Overview-23[]
*Teacher Work Day*
//tag::Assignment-091[]
===== Monday, January 6, 2025
*Satellite Day*

//end::Assignment-091[]
*First Day Back in Class*
//tag::Assignment-092[]
===== Tuesday, January 7, 2025

//end::Assignment-092[]
//tag::Assignment-093[]
===== Wednesday, January 8, 2025

//end::Assignment-093[]
//tag::Assignment-094[]
===== Thursday, January 9, 2025

//end::Assignment-094[]
//tag::Assignment-095[]
===== Friday, January 10, 2025

//end::Assignment-095[]
//tag::Quiz-14[]
Quiz 14

//end::Quiz-14[]
//end::Week-23[]

==== Week 24
//tag::Week-24[]
//tag::Weekly-Overview-24[]
24

//end::Weekly-Overview-24[]

//tag::Assignment-096[]
===== Monday, January 13, 2025

//end::Assignment-096[]
//tag::Assignment-097[]
===== Tuesday, January 14, 2025

//end::Assignment-097[]
//tag::Assignment-098[]
===== Wednesday, January 15, 2025

//end::Assignment-098[]
//tag::Assignment-099[]
===== Thursday, January 16, 2025

//end::Assignment-099[]
//tag::Assignment-100[]
===== Friday, January 17, 2025

//end::Assignment-100[]
//tag::Quiz-15[]
Quiz 15

//end::Quiz-15[]
//end::Week-24[]


==== Week 25
//tag::Week-25[]
Review Chapters 18-21
//tag::Weekly-Overview-25[]
25

//end::Weekly-Overview-25[]
//tag::Assignment-101[]
===== Monday, January 20, 2025
*Holiday-MLK Day*

//end::Assignment-101[]
//tag::Assignment-102[]
===== Tuesday, January 21, 2025

//end::Assignment-102[]
//tag::Assignment-103[]
===== Wednesday, January 22, 2025

//end::Assignment-103[]
//tag::Assignment-104[]
===== Thursday, January 23, 2025

//end::Assignment-104[]
//tag::Assignment-105[]
===== Friday, January 24, 2025

//end::Assignment-105[]
//tag::Quiz-16[]
Quiz 16

//end::Quiz-16[]
//end::Week-25[]

==== Week 26
//tag::Week-26[]
Review Chapters 22-24
//tag::Weekly-Overview-26[]
26

//end::Weekly-Overview-26[]
//tag::Assignment-106[]
===== Monday, January 27, 2025

//end::Assignment-106[]
//tag::Assignment-107[]
===== Tuesday, January 28, 2025

//end::Assignment-107[]
//tag::Assignment-108[]
===== Wednesday, January 29, 2025

//end::Assignment-108[]
//tag::Assignment-109[]
===== Thursday, January 30, 2025

//end::Assignment-109[]
//tag::Assignment-110[]
===== Friday, January 31, 2025

//end::Assignment-110[]
//tag::Test-05[]
Test 5

//end::Test-05[]
//end::Week-26[]

=== Module 6 -- Chapters 35-36
==== Week 27
//tag::Week-27[]
Review Chapters 25-27
//tag::Weekly-Overview-27[]
27

//end::Weekly-Overview-27[]
//tag::Assignment-111[]
===== Monday, February 3, 2025

//end::Assignment-111[]
//tag::Assignment-112[]
===== Tuesday, February 4, 2025

//end::Assignment-112[]
//tag::Assignment-113[]
===== Wednesday, February 5, 2025

//end::Assignment-113[]
//tag::Assignment-114[]
===== Thursday, February 6, 2025

//end::Assignment-114[]
//tag::Assignment-115[]
===== Friday, February 7, 2025

//end::Assignment-115[]
//tag::Quiz-17[]
Quiz 17

//end::Quiz-17[]
//end::Week-27[]


==== Week 28
//tag::Week-28[]
//tag::Weekly-Overview-28[]
28

//end::Weekly-Overview-28[]
//tag::Assignment-116[]
===== Monday, February 10, 2025

//end::Assignment-116[]
//tag::Assignment-117[]
===== Tuesday, February 11, 2025

//end::Assignment-117[]
//tag::Assignment-118[]
===== Wednesday, February 12, 2025

//end::Assignment-118[]
//tag::Assignment-119[]
===== Thursday, February 13, 2025

//end::Assignment-119[]
//tag::Assignment-120[]
===== Friday, February 14, 2025

//end::Assignment-120[]
//tag::Quiz-18[]
Quiz 18

//end::Quiz-18[]
//end::Week-28[]

==== Week 29
//tag::Week-29[]
//tag::Weekly-Overview-29[]
29

//end::Weekly-Overview-29[]
//tag::Assignment-121[]
===== Monday, February 17, 2025

//end::Assignment-121[]
//tag::Assignment-122[]
===== Tuesday, February 18, 2025

//end::Assignment-122[]
//tag::Assignment-123[]
===== Wednesday, February 19, 2025

//end::Assignment-123[]
//tag::Assignment-124[]
===== Thursday, February 20, 2025

//end::Assignment-124[]
//tag::Assignment-125[]
===== Friday, February 21, 2025
*Winter Holiday*

//end::Assignment-125[]
//tag::Quiz-19[]
Quiz 19

//end::Quiz-19[]

//end::Week-29[]


==== Week 30
//tag::Week-30[]
//tag::Weekly-Overview-30[]
30

//end::Weekly-Overview-30[]

//tag::Assignment-126[]
===== Monday, February 24, 2025

//end::Assignment-126[]
//tag::Assignment-127[]
===== Tuesday, February 25, 2025

//end::Assignment-127[]
//tag::Assignment-128[]
===== Wednesday, February 26, 2025

//end::Assignment-128[]
//tag::Assignment-129[]
===== Thursday, February 27, 2025

//end::Assignment-129[]
//tag::Assignment-130[]
===== Friday, February 28, 2025

//end::Assignment-130[]
//tag::Quiz-20[]
Quiz 20

//end::Quiz-20[]
//end::Week-30[]

==== Week 31
//tag::Week-31[]
//tag::Weekly-Overview-31[]
31

//end::Weekly-Overview-31[]
//tag::Assignment-131[]
===== Monday, March 3, 2025

//end::Assignment-131[]
//tag::Assignment-132[]
===== Tuesday, March 4, 2025

//end::Assignment-132[]
//tag::Assignment-133[]
===== Wednesday, March 5, 2025

//end::Assignment-133[]
//tag::Assignment-134[]
===== Thursday, March 6, 2025

//end::Assignment-134[]
//tag::Assignment-135[]
===== Friday, March 7, 2025

//end::Assignment-135[]
//tag::Test-06[]
Test 6

//end::Test-06[]
//end::Week-31[]


== 4th Quarter
=== Module 7 -- Chapters 37-38
==== Week 32
//tag::Week-32[]
//tag::Weekly-Overview-32[]
32

//end::Weekly-Overview-32[]
//tag::Assignment-136[]
===== Monday, March 10, 2025

//end::Assignment-136[]
//tag::Assignment-137[]
===== Tuesday, March 11, 2025

//end::Assignment-137[]
//tag::Assignment-138[]
===== Wednesday, March 12, 2025

//end::Assignment-138[]
//tag::Assignment-139[]
===== Thursday, March 13, 2025

//end::Assignment-139[]
//tag::Assignment-140[]
===== Friday, March 14, 2025

//end::Assignment-140[]
//tag::Quiz-21[]
Quiz 21

//end::Quiz-21[]
//end::Week-32[]


==== Week 33
//tag::Week-33[]
//tag::Weekly-Overview-33[]
33

//end::Weekly-Overview-33[]

//tag::Assignment-141[]
===== Monday, March 17, 2025

//end::Assignment-141[]
//tag::Assignment-142[]
===== Tuesday, March 18, 2025
*Seminar Day*


//end::Assignment-142[]
//tag::Assignment-143[]
===== Wednesday, March 19, 2025

//end::Assignment-143[]
//tag::Assignment-144[]
===== Thursday, March 20, 2025

//end::Assignment-144[]
//tag::Assignment-145[]
===== Friday, March 21, 2025

//end::Assignment-145[]
//tag::Quiz-22[]
Quiz 22

//end::Quiz-22[]
//end::Week-33[]

==== Week 34
//tag::Week-34[]
//tag::Weekly-Overview-34[]
34

//end::Weekly-Overview-34[]

//tag::Assignment-146[]
===== Monday, March 24, 2025

//end::Assignment-146[]
//tag::Assignment-147[]
===== Tuesday, March 25, 2025

//end::Assignment-147[]
//tag::Assignment-148[]
===== Wednesday, March 26, 2025

//end::Assignment-148[]
//tag::Assignment-149[]
===== Thursday, March 27, 2025

//end::Assignment-149[]
//tag::Assignment-150[]
===== Friday, March 28, 2025

//end::Assignment-150[]
//tag::Quiz-23[]
Quiz 23

//end::Quiz-23[]
//end::Week-34[]




==== Week 35
//tag::Week-35[]
//tag::Weekly-Overview-35[]
35

//end::Weekly-Overview-35[]

//tag::Assignment-151[]
===== Monday, March 31, 2025

//end::Assignment-151[]
//tag::Assignment-152[]
===== Tuesday, April 1, 2025

//end::Assignment-152[]
//tag::Assignment-153[]
===== Wednesday, April 2, 2025

//end::Assignment-153[]
//tag::Assignment-154[]
===== Thursday, April 3, 2025

//end::Assignment-154[]
//tag::Assignment-155[]
===== Friday, April 4, 2025

//end::Assignment-155[]
//tag::Test-07[]
Test 7

//end::Test-07[]
//end::Week-35[]

=== Module 8 -- Chapter 39

==== Week 36
//tag::Week-36[]
//tag::Weekly-Overview-36[]
36

//end::Weekly-Overview-36[]


//end::Week-36[]

==== Week 37
//tag::Week-37[]
//tag::Weekly-Overview-37[]
37

//end::Weekly-Overview-37[]
//tag::Assignment-156[]
===== Monday, April 14, 2025

//end::Assignment-156[]
//tag::Assignment-157[]
===== Tuesday, April 15, 2025

//end::Assignment-157[]
//tag::Assignment-158[]
===== Wednesday, April 16, 2025

//end::Assignment-158[]
//tag::Assignment-159[]
===== Thursday, April 17, 2025

//end::Assignment-159[]
//tag::Assignment-160[]
===== Friday, April 18, 2025

//end::Assignment-160[]
//tag::Quiz-24[]
Quiz 24

//end::Quiz-24[]
//end::Week-37[]

==== Week 38
//tag::Week-38[]
//tag::Weekly-Overview-38[]
38

//end::Weekly-Overview-38[]

//tag::Assignment-161[]
===== Monday, April 21, 2025

//end::Assignment-161[]
//tag::Assignment-162[]
===== Tuesday, April 22, 2025

//end::Assignment-162[]
//tag::Assignment-163[]
===== Wednesday, April 23, 2025

//end::Assignment-163[]
//tag::Assignment-164[]
===== Thursday, April 24, 2025

//end::Assignment-164[]
//tag::Assignment-165[]
===== Friday, April 25, 2025

//end::Assignment-165[]
//tag::Quiz-25[]
Quiz 25

//end::Quiz-25[]
//end::Week-38[]

==== Week 39
//tag::Week-39[]
//tag::Weekly-Overview-39[]
39

//end::Weekly-Overview-39[]

//tag::Assignment-166[]
===== Monday, April 28, 2025

//end::Assignment-166[]
//tag::Assignment-167[]
===== Tuesday, April 29, 2025

//end::Assignment-167[]
//tag::Assignment-168[]
===== Wednesday, April 30, 2025

//end::Assignment-168[]
//tag::Assignment-169[]
===== Thursday, May 1, 2025

//end::Assignment-169[]
//tag::Assignment-170[]
===== Friday, May 2, 2025

//end::Assignment-170[]
//tag::Quiz-26[]
Quiz 26

//end::Quiz-26[]
//end::Week-39[]


==== Week 40
//tag::Week-40[]
//tag::Weekly-Overview-40[]
40

//end::Weekly-Overview-40[]

//tag::Assignment-171[]
===== Monday, May 5, 2025

//end::Assignment-171[]
//tag::Assignment-172[]
===== Tuesday, May 6, 2025

//end::Assignment-172[]
//tag::Assignment-173[]
===== Wednesday, May 7, 2025

//end::Assignment-173[]
//tag::Assignment-174[]
===== Thursday, May 8, 2025

//end::Assignment-174[]
//tag::Assignment-175[]
===== Friday, May 9, 2025

//end::Assignment-175[]
//tag::Quiz-27[]
Quiz 27

//end::Quiz-27[]
//end::Week-40[]

==== Week 41
//tag::Week-41[]
//tag::Weekly-Overview-41[]
41

//end::Weekly-Overview-41[]

//tag::Assignment-176[]
===== Monday, May 12, 2025

//end::Assignment-176[]
//tag::Assignment-177[]
===== Tuesday, May 13, 2025

//end::Assignment-177[]
//tag::Assignment-178[]
===== Wednesday, May 14, 2025

//end::Assignment-178[]
//tag::Assignment-179[]
===== Thursday, May 15, 2025

//end::Assignment-179[]
//tag::Assignment-180[]
===== Friday, May 16, 2025

//end::Assignment-180[]
//tag::Test-08[]
Test 8

//end::Test-08[]
//end::Week-41[]







